events {}

http {
    server {
        listen 80;

        # Monolito Django (todo lo existente)
        location / {
            proxy_pass http://django_web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Microservicio estrangulado: notificaciones
        location /api/v2/notificaciones/ {
            proxy_pass http://flask_notificaciones:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}