# Generated by Django 5.2.17 on 2026-09-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_producto_categoria_direccionenvio_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='es_creadora',
            field=models.BooleanField(default=False),
        ),
    ]
